type: 'baidu_40000'
raw_label_path: '/media/jw11/54E2ACF3E2ACDA8E/m1_3d_new'
label_file_tree: '*/workspace/data/new_save/*/point_cloud_3d/*.json'
pcd_file_tree : '*/workspace/data/new_save/*/velodyne_points/unde*.pcd'
root_path: '/media/jw11/54E2ACF3E2ACDA8E/m1_3d_new'
save_path: '/media/jw11/54E2ACF3E2ACDA8E/baidu_40000/training'
sensor_lib: ['velodyne','label_2']